### ISSUE TITLE
About evaluation on Tanks and Temple dataset

### ISSUE THREAD

**Issue by g32321** [jzhangbs/Vis-MVSNet#19]
Hi, jzhangbs, thx for your great work. While, recently, i test the proposed net on t&t dataset(intermediate) using the pretrained params, but the result is abnormal, the final result is 47.90, while the official online result is 60.03. The following is my testing params, can you give me some advice?
==depth_prediction==
max_d = 256
interval_scale = 1
cas_depth_num 64,32,16
cas_interv_scale 4,2,1
num_src=7
--fusion--
vthresh=4
pthresh 0.8,0.7,0.8
------------------------
Result
F-score: 47.90
Recall:72.04
Precision:36.81
---------------------
All the params are following the original paper and the propose code
Im look forward to hearing from you. :)

**Comment by isshenye** [comment]
> ## Hi, jzhangbs, thx for your great work. While, recently, i test the proposed net on t&t dataset(intermediate) using the pretrained params, but the result is abnormal, the final result is 47.90, while the official online result is 60.03. The following is my testing params, can you give me some advice?
> ==depth_prediction==
> max_d = 256
> interval_scale = 1
> cas_depth_num 64,32,16
> cas_interv_scale 4,2,1
> num_src=7
> --fusion--
> vthresh=4
> pthresh 0.8,0.7,0.8
> ## Result
> F-score: 47.90
> Recall:72.04
> Precision:36.81
> 
> All the params are following the original paper and the propose code
> Im look forward to hearing from you. :)

hello, we encounter some problem when we use the command "**python test.py --data_root /home/amax/shenpeizhangmodle/Vis-MVSNet-master/database/tankandtemples --dataset_name tanksandtemples --load_path /home/amax/shenpeizhangmodle/Vis-MVSNet-master/pretrained_model/vis --result_dir /home/amax/shenpeizhangmodle/Vis-MVSNet-master/save11**"

the error is:
```
Traceback (most recent call last):
  File "test.py", line 99, in <module>
    outputs, refined_depth, prob_maps = model(sample, cas_depth_num, cas_interv_scale, mode=args.mode)
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/amax/anaconda3/envs/MVSNet_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 3 required positional arguments: 'sample', 'depth_nums', and 'interval_scales'

```
have you ever handle this problem?can you tell me what's your commands? thank you very much!
